landscape-dense-maas:
  services:
    apache2:
      charm: cs:trusty/apache2-10
      num_units: 1
      to:
      - lxc:0
      options:
        enable_modules: proxy proxy_http proxy_balancer rewrite expires headers ssl
        ssl_cert: SELFSIGNED
        ssl_certlocation: apache2.cert
        ssl_keylocation: apache2.key
    haproxy:
      charm: cs:trusty/haproxy-4
      num_units: 1
      to:
      - lxc:0
      options:
        default_timeouts: queue 60000, connect 5000, client 120000, server 120000
        enable_monitoring: true
        monitoring_allowed_cidr: 0.0.0.0/0
        monitoring_password: haproxy
        services: ""
    landscape:
      charm: cs:trusty/landscape-server
      num_units: 1
      to:
      - lxc:0
      options:
        landscape-password: {{ landscape_password }}
        repository: http://ppa.launchpad.net/landscape/15.01/ubuntu
        service-count: "2"
        services: static appserver pingserver combo-loader async-frontend apiserver
          package-upload jobhandler package-search cron juju-sync
      constraints: mem=2048
    landscape-msg:
      charm: cs:trusty/landscape-server
      num_units: 1
      to:
      - lxc:0
      options:
        landscape-password: {{ landscape_password }}
        repository: http://ppa.launchpad.net/landscape/15.01/ubuntu
        services: msgserver
      constraints: mem=2048
    postgresql:
      charm: cs:trusty/postgresql-15
      num_units: 1
      to:
      - lxc:0
      options:
        extra-packages: python-apt postgresql-contrib postgresql-.*-debversion
        max_connections: 500
      constraints: mem=2048
    rabbitmq-server:
      charm: cs:trusty/rabbitmq-server-26
      num_units: 1
      to:
      - lxc:0
  machines:
    "0": {}
  series: trusty
  relations:
  - - landscape
    - rabbitmq-server
  - - landscape
    - haproxy
  - - landscape:vhost-config
    - apache2:vhost-config
  - - landscape:db-admin
    - postgresql:db-admin
  - - haproxy:website
    - apache2:reverseproxy
  - - landscape-msg
    - rabbitmq-server
  - - landscape-msg
    - haproxy
  - - landscape-msg:db-admin
    - postgresql:db-admin